'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class setGoal
    
    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnAvatar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnAvatar As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lbName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbDowId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDowId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbDepartName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDepartName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbAccountType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAccountType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadPanelBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPanelBar1 As Global.Telerik.Web.UI.RadPanelBar
    
    '''<summary>
    '''rcbYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbYear As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbMonth As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''chkUpdateAllYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUpdateAllYear As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''srcDepartmentList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcDepartmentList As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rgGoalSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgGoalSetting As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''pnEditMTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnEditMTP As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbn_editpercentLeadershipFieldVisibility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbn_editpercentLeadershipFieldVisibility As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''tbn_editpercentActionCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbn_editpercentActionCompleted As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''btUpdateMTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btUpdateMTP As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btCloseMTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCloseMTP As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hftotalSecondEyeSafety control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hftotalSecondEyeSafety As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hftotalPSCE_ContainmentLoss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hftotalPSCE_ContainmentLoss As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hftotalPSCE_PSNM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hftotalPSCE_PSNM As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfcomplianceProactive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfcomplianceProactive As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager
End Class
