'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class setUserbyDepart
    
    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnAvatar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnAvatar As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lbName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbDowId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDowId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbDepartName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDepartName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbAccountType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAccountType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadPanelBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPanelBar1 As Global.Telerik.Web.UI.RadPanelBar
    
    '''<summary>
    '''RadTabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''RadMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView1 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''tbDowId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDowId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSurname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rcbDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbDepartment As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcDepartment As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rcbJobLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbJobLevel As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''imbtNewJobLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtNewJobLevel As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''chkEnUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnUser As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btAddUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btAddUser As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btCancelUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCancelUser As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''rgEmployeeLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgEmployeeLast As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''srcEmployeeLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcEmployeeLast As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''RadPageView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView2 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''tbSearchKeyword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSearchKeyword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btSearchBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSearchBox As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgbClearKeyword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbClearKeyword As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''rgEmployeeList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgEmployeeList As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''srcEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcEmployee As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''cbShow_Del control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbShow_Del As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RadPageView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView3 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''hfEmployeeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfEmployeeId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tbDowId_Acc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDowId_Acc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbName_Acc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbName_Acc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbSurname_Acc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSurname_Acc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbEmail_Acc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEmail_Acc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbDiaplay_Acc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDiaplay_Acc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbDepart_Acc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDepart_Acc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbJoblv_Acc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbJoblv_Acc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hfRoleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRoleName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''RadMultiPage2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage2 As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadMultiPage2_Create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage2_Create As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''rcbAccountType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbAccountType As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcAccountType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcAccountType As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUsername As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbPasswordConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPasswordConfirm As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbErrorMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btCreateAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCreateAccount As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btBack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RadMultiPage2_Change control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage2_Change As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''rcbAccountType_Change control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbAccountType_Change As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''tbUsername_Change control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUsername_Change As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hfUsername_Ori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfUsername_Ori As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfAspNetUserId_Ori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAspNetUserId_Ori As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tbEmail_Change control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEmail_Change As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbErrorMsg_Change control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbErrorMsg_Change As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btEditAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btEditAccount As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btBack_Change control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btBack_Change As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btResetPassword_Change control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btResetPassword_Change As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btDeleteAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btDeleteAccount As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RadMultiPage2_Reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage2_Reset As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''tbUsername_Reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUsername_Reset As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbPassword_Reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPassword_Reset As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbPasswordConfirm_Reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPasswordConfirm_Reset As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbErrorMsg_Reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbErrorMsg_Reset As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btResetPassword_Reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btResetPassword_Reset As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btBack_Reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btBack_Reset As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RadMultiPage2_Delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage2_Delete As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''tbUsername_Delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUsername_Delete As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btConfirmDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btConfirmDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btBack_Delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btBack_Delete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager
End Class
