'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class observer
    
    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager
    
    '''<summary>
    '''lbName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbDowId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDowId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbDepartName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDepartName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbAccountType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAccountType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadPanelBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPanelBar1 As Global.Telerik.Web.UI.RadPanelBar
    
    '''<summary>
    '''hfOwnerEmpId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOwnerEmpId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''rcbDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbDepartment As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcDepartment As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''btNewObserv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btNewObserv As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RadAjaxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel1 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''lbActionNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbActionNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hfRecId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRecId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''rdpDocDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpDocDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rcbTimeHH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbTimeHH As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbTimeMM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbTimeMM As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbDurationH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbDurationH As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbDurationM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbDurationM As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''imgAddEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddEntry As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''tbMyFullname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMyFullname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbMyDowId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMyDowId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbMyDepart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMyDepart As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadAjaxPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel2 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''racObservBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racObservBox As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''srcAutoName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcAutoName As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''imbtFindObserv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindObserv As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''hfEmpIdSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfEmpIdSelect As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfFullNameSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFullNameSelect As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pnOtherObserver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnOtherObserver As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rgObserverList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgObserverList As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''srcObserverList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcObserverList As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rcbNoObserve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbNoObserve As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''tokenInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tokenInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadAjaxPanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel3 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''rtabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtabStrip1 As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''srcCategory0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcCategory0 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''RadMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView1 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''tbTitle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTitle1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rcbCategory1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCategory1 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbCategorySub1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCategorySub1 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcCategorySub1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcCategorySub1 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rcbFailurePoint1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFailurePoint1 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcFailurePoint1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcFailurePoint1 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbEquipment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEquipment1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkHRO1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk2Eye1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk2Eye1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkRecognition1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRecognition1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkSendEmail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendEmail1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''hfPnHRO1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPnHRO1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pnHRO1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnHRO1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkHRO1op1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO1op1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO1op2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO1op2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO1op3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO1op3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO1op4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO1op4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO1op5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO1op5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rcbObserveType1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbObserveType1 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadAjaxPanel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel11 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''rcbContractor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbContractor1 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadAjaxPanel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel12 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''RadUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadUpload1 As Global.Telerik.Web.UI.RadAsyncUpload
    
    '''<summary>
    '''lbUploadInfo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUploadInfo1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btUploadImg1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btUploadImg1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnShowImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnShowImage1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PictureList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PictureList1 As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''srcPicture1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcPicture1 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbDescription1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDescription1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadAjaxPanel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel13 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''tbAction1a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction1a As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon1a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon1a As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtOtherAction1a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtOtherAction1a As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon1a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon1a As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnRespon1b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRespon1b As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbAction1b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction1b As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon1b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon1b As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtCloseAction1b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtCloseAction1b As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtOtherAction1b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtOtherAction1b As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon1b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon1b As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnRespon1c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRespon1c As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbAction1c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction1c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon1c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon1c As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtCloseAction1c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtCloseAction1c As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon1c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon1c As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''RadPageView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView2 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''tbTitle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTitle2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rcbCategory2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCategory2 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbCategorySub2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCategorySub2 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcCategorySub2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcCategorySub2 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rcbFailurePoint2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFailurePoint2 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcFailurePoint2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcFailurePoint2 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbEquipment2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEquipment2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkHRO2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk2Eye2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk2Eye2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkRecognition2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRecognition2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkSendEmail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendEmail2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''hfPnHRO2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPnHRO2 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pnHRO2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnHRO2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkHRO2op1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO2op1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO2op2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO2op2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO2op3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO2op3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO2op4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO2op4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO2op5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO2op5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rcbObserveType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbObserveType2 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadAjaxPanel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel21 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''rcbContractor2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbContractor2 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadAjaxPanel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel22 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''RadUpload2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadUpload2 As Global.Telerik.Web.UI.RadAsyncUpload
    
    '''<summary>
    '''lbUploadInfo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUploadInfo2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btUploadImg2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btUploadImg2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnShowImage2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnShowImage2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PictureList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PictureList2 As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''srcPicture2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcPicture2 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbDescription2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDescription2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadAjaxPanel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel23 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''tbAction2a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction2a As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon2a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon2a As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtOtherAction2a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtOtherAction2a As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon2a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon2a As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnRespon2b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRespon2b As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbAction2b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction2b As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon2b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon2b As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtCloseAction2b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtCloseAction2b As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtOtherAction2b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtOtherAction2b As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon2b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon2b As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnRespon2c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRespon2c As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbAction2c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction2c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon2c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon2c As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtCloseAction2c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtCloseAction2c As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon2c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon2c As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''RadPageView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView3 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''tbTitle3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTitle3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rcbCategory3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCategory3 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbCategorySub3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCategorySub3 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcCategorySub3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcCategorySub3 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rcbFailurePoint3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFailurePoint3 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcFailurePoint3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcFailurePoint3 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbEquipment3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEquipment3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkHRO3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk2Eye3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk2Eye3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkRecognition3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRecognition3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkSendEmail3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendEmail3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''hfPnHRO3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPnHRO3 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pnHRO3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnHRO3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkHRO3op1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO3op1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO3op2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO3op2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO3op3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO3op3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO3op4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO3op4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO3op5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO3op5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rcbObserveType3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbObserveType3 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadAjaxPanel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel31 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''rcbContractor3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbContractor3 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadAjaxPanel32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel32 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''RadUpload3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadUpload3 As Global.Telerik.Web.UI.RadAsyncUpload
    
    '''<summary>
    '''lbUploadInfo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUploadInfo3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btUploadImg3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btUploadImg3 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnShowImage3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnShowImage3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PictureList3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PictureList3 As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''srcPicture3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcPicture3 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbDescription3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDescription3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadAjaxPanel33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel33 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''tbAction3a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction3a As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon3a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon3a As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtOtherAction3a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtOtherAction3a As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon3a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon3a As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnRespon3b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRespon3b As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbAction3b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction3b As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon3b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon3b As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtCloseAction3b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtCloseAction3b As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtOtherAction3b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtOtherAction3b As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon3b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon3b As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnRespon3c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRespon3c As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbAction3c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction3c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon3c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon3c As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtCloseAction3c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtCloseAction3c As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon3c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon3c As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''RadPageView4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView4 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''tbTitle4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTitle4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rcbCategory4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCategory4 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbCategorySub4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCategorySub4 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcCategorySub4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcCategorySub4 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rcbFailurePoint4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFailurePoint4 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcFailurePoint4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcFailurePoint4 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbEquipment4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEquipment4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkHRO4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk2Eye4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk2Eye4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkRecognition4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRecognition4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkSendEmail4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendEmail4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''hfPnHRO4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPnHRO4 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pnHRO4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnHRO4 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkHRO4op1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO4op1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO4op2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO4op2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO4op3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO4op3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO4op4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO4op4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO4op5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO4op5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rcbObserveType4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbObserveType4 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadAjaxPanel41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel41 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''rcbContractor4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbContractor4 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadAjaxPanel42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel42 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''RadUpload4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadUpload4 As Global.Telerik.Web.UI.RadAsyncUpload
    
    '''<summary>
    '''lbUploadInfo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUploadInfo4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btUploadImg4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btUploadImg4 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnShowImage4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnShowImage4 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PictureList4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PictureList4 As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''srcPicture4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcPicture4 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbDescription4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDescription4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadAjaxPanel43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel43 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''tbAction4a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction4a As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon4a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon4a As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtOtherAction4a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtOtherAction4a As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon4a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon4a As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnRespon4b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRespon4b As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbAction4b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction4b As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon4b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon4b As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtCloseAction4b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtCloseAction4b As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtOtherAction4b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtOtherAction4b As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon4b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon4b As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnRespon4c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRespon4c As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbAction4c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction4c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon4c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon4c As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtCloseAction4c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtCloseAction4c As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon4c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon4c As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''RadPageView5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView5 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''tbTitle5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTitle5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rcbCategory5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCategory5 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbCategorySub5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCategorySub5 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcCategorySub5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcCategorySub5 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rcbFailurePoint5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFailurePoint5 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcFailurePoint5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcFailurePoint5 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbEquipment5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEquipment5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkHRO5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk2Eye5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk2Eye5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkRecognition5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRecognition5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkSendEmail5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendEmail5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''hfPnHRO5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPnHRO5 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pnHRO5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnHRO5 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkHRO5op1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO5op1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO5op2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO5op2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO5op3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO5op3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO5op4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO5op4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO5op5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO5op5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rcbObserveType5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbObserveType5 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadAjaxPanel51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel51 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''rcbContractor5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbContractor5 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadAjaxPanel52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel52 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''RadUpload5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadUpload5 As Global.Telerik.Web.UI.RadAsyncUpload
    
    '''<summary>
    '''lbUploadInfo5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUploadInfo5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btUploadImg5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btUploadImg5 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnShowImage5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnShowImage5 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PictureList5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PictureList5 As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''srcPicture5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcPicture5 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbDescription5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDescription5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadAjaxPanel53 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel53 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''tbAction5a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction5a As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon5a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon5a As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtOtherAction5a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtOtherAction5a As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon5a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon5a As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnRespon5b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRespon5b As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbAction5b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction5b As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon5b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon5b As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtCloseAction5b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtCloseAction5b As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtOtherAction5b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtOtherAction5b As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon5b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon5b As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnRespon5c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRespon5c As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbAction5c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction5c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon5c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon5c As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtCloseAction5c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtCloseAction5c As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon5c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon5c As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''RadPageView6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView6 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''tbTitle6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTitle6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rcbCategory6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCategory6 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbCategorySub6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCategorySub6 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcCategorySub6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcCategorySub6 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rcbFailurePoint6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFailurePoint6 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcFailurePoint6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcFailurePoint6 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbEquipment6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEquipment6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkHRO6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk2Eye6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk2Eye6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkRecognition6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRecognition6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkSendEmail6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendEmail6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''hfPnHRO6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPnHRO6 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pnHRO6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnHRO6 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkHRO6op1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO6op1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO6op2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO6op2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO6op3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO6op3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO6op4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO6op4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHRO6op5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHRO6op5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rcbObserveType6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbObserveType6 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadAjaxPanel61 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel61 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''rcbContractor6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbContractor6 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadAjaxPanel62 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel62 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''RadUpload6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadUpload6 As Global.Telerik.Web.UI.RadAsyncUpload
    
    '''<summary>
    '''lbUploadInfo6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUploadInfo6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btUploadImg6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btUploadImg6 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnShowImage6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnShowImage6 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PictureList6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PictureList6 As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''srcPicture6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcPicture6 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbDescription6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDescription6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadAjaxPanel63 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel63 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''tbAction6a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction6a As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon6a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon6a As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtOtherAction6a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtOtherAction6a As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon6a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon6a As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnRespon6b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRespon6b As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbAction6b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction6b As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon6b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon6b As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtCloseAction6b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtCloseAction6b As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtOtherAction6b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtOtherAction6b As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon6b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon6b As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnRespon6c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRespon6c As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbAction6c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAction6c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''racRespon6c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents racRespon6c As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''imbtCloseAction6c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtCloseAction6c As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imbtFindRespon6c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbtFindRespon6c As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''RadAjaxPanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel4 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''pnSaveAndSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnSaveAndSend As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''srcContractor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcContractor As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''btSaveAndSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSaveAndSend As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''infobox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infobox As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''pnSendEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnSendEmail As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lbActionNumberComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbActionNumberComplete As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''srcSendEmailList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcSendEmailList As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rgEmailList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgEmailList As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''srcSendListEachOb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcSendListEachOb As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''chkSendEachObserve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendEachObserve As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnSendEachObserve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnSendEachObserve As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rgEmailListEachOb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgEmailListEachOb As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''btSendEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSendEmail As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btObservationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btObservationList As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btNewObserve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btNewObserve As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''RadWindowManager2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager2 As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''rwEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwEmployee As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel
End Class
