'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class autoReport
    
    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lbName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbDowId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDowId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbDepartName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDepartName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbAccountType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAccountType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadPanelBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPanelBar1 As Global.Telerik.Web.UI.RadPanelBar
    
    '''<summary>
    '''infobox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infobox As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''rcbIsAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbIsAuto As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbMonth As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbYear2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbYear2 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''btStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btStart As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hfInProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfInProgress As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfCurrentMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCurrentMonth As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfTotalObserver_fsfl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTotalObserver_fsfl As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfManPowerWorkingHourPerMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfManPowerWorkingHourPerMonth As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lbStartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbStartTime As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCurrentMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCurrentMonth As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCurrent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbOverAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbOverAll As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCountInterval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCountInterval As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_totalActionNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_totalActionNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_totalObserv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_totalObserv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_actionNumComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_actionNumComplete As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_actionNumRecog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_actionNumRecog As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_percentActionComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_percentActionComplete As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_observeComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_observeComplete As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_observeRecognition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_observeRecognition As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_PSCE_ContainmentLossCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_PSCE_ContainmentLossCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_PSCE_PSNMCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_PSCE_PSNMCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_sumOfDuration_fsfl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_sumOfDuration_fsfl As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_percentLeadershipVisibility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_percentLeadershipVisibility As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_proactiveCompliance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_proactiveCompliance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_secondEye control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_secondEye As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_injuryNearMiss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_injuryNearMiss As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_reliability_wHRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_reliability_wHRO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_quality_wHRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_quality_wHRO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_reliability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_reliability As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_percentOfiIdentified control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_percentOfiIdentified As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_percentPUPFieldAss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_percentPUPFieldAss As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_percentLCSFieldAss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_percentLCSFieldAss As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_offHourCountStr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_offHourCountStr As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lb_percentOffHour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_percentOffHour As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnTimeOffset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnTimeOffset As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rdpCallTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpCallTime As Global.Telerik.Web.UI.RadTimePicker
    
    '''<summary>
    '''rcbDepartment2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbDepartment2 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''imgClock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgClock As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''btSetOffset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSetOffset As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rcbInterval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbInterval As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Timer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Timer1 As Global.System.Web.UI.Timer
    
    '''<summary>
    '''rcbYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbYear As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbDepartment As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcDepartment As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''btViewReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btViewReport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btGenReportSelMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btGenReportSelMonth As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btGenReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btGenReport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btViewChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btViewChart As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnSelMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnSelMonth As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Gen1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gen1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Gen2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gen2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Gen3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gen3 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Gen4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gen4 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Gen5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gen5 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Gen6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gen6 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Gen7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gen7 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Gen8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gen8 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Gen9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gen9 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Gen10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gen10 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Gen11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gen11 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Gen12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gen12 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''srcIndicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcIndicator As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rlvIndicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rlvIndicator As Global.Telerik.Web.UI.RadListView
    
    '''<summary>
    '''lbLastUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLastUpdate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbValidateInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbValidateInfo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rcbMonthValidate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbMonthValidate As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbYearValidate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbYearValidate As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''btValidate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btValidate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hfInProgress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfInProgress2 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfLoopStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLoopStart As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfPercentUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPercentUpdate As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lbStartTime2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbStartTime2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCurrent2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCurrent2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbOverAll2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbOverAll2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPercent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Timer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Timer2 As Global.System.Web.UI.Timer
    
    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tbnIntervalAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbnIntervalAdmin As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''tbnIntervalUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbnIntervalUser As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''btSaveInterval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSaveInterval As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lbSaveInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSaveInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager
End Class
