'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class rpHistoricalData
    
    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager
    
    '''<summary>
    '''lbName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbDowId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDowId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbDepartName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDepartName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbAccountType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAccountType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadPanelBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPanelBar1 As Global.Telerik.Web.UI.RadPanelBar
    
    '''<summary>
    '''rcbSelectYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbSelectYear As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbSelectMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbSelectMonth As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''rcbDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbDepartment As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''srcDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcDepartment As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''btSearchHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSearchHistory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chkOnly_fsfl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOnly_fsfl As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''srcHistoricalData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcHistoricalData As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rgRecordList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgRecordList As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager
End Class
